title: "Apuntes para PotSM"
description: "Apoyo para partidas y creación de personajes"
plugins: jekyll-remote-theme # add this line to the plugins list if you already have one
url: "https://SamuMSeoane.github.io"
baseurl: "/PotSM_Apuntes"
remote_theme: pages-themes/merlot@v0.2.0